[package]
name = "rustynuc"
version = "0.1.0"
authors = ["Johnny Debebe <28043284+bjohnnyd@users.noreply.github.com>"]
edition = "2018"
publish = false

[workspace]
members = ["oxo"]

[dependencies]
niffler = "2.1.0"
structopt = "0.3.14"
oxo = { path = "oxo" }

[dev-dependencies]
predicates = "1.0.4"
assert_cmd = "1.0.1"
