# On every push this script is executed
on:
  push:
    branches:
      - gh-pages
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@gh-pages
    # Build & deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.12.0
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.TOKEN }}
